### PR TITLE
alphanumeric order of groups and sign of the fold change

### PR DESCRIPTION
**Pull request by oheil**
My last code example was not clear enough and not complete to clarify the issue.

The issue is ONLY about what happens when you swap the group identifiers in the
phenodata.

> Now, if you swap the sample groups in phenodata (=assign the controls and samples the other way around), this naturally changes the fold changes. 

This is only true for "Empirical Bayes". All other methods do not swap the sign!
I would say, that the second (not changing sign) should be the desired behaviour,
because there is nothing which makes the use of numbers as group identifiers
and the number 1 as the control identifier explicit or as a natural choice.

There are only two methods in stat-two-groups.R which produce a fold change
column. "Empirical Bayes" and "RankProd". They do not behave equal, because
"RankProd" uses only "unique" on the group IDs resulting in not changing sign
when the group IDs are exchanged.

Calculating fold change using the tool "Calculate fold change" in calculate-fold-change.R does change the sign neither.

The following code shows the results for each of the above methods for the fold change. The code lines are those from the original files currently in use:
```
library(multtest)
library(limma)
adj.method<-"BH"
dat2<-matrix(c(1,2,1,2,2,1,2,1,8,7,8,9,8,7,8,9),ncol=4)
dat2
groups<-c(2,2,1,1)

#Empirical Bayes
pairing <- "EMPTY"
design<-model.matrix(~as.factor(groups))
fit <- lmFit(dat2, design)
fit <- eBayes(fit)
tab <- toptable(fit, coef=2, number=nrow(fit), adjust.method=adj.method, sort.by="none")
p <- tab$adj.P.Val
M <- tab$logFC

#RankProd
dat2.1 <-dat2[,groups==unique(groups)[1]]
dat2.2 <-dat2[,groups==unique(groups)[2]]
rp.fold.change <- apply(dat2.1, 1, mean, na.rm=T) - apply(dat2.2, 1, mean, na.rm=T)

#calculate-fold-change
columnnames<-c()
dat3<-matrix(nrow=nrow(dat2), ncol=length(unique(groups)), NA)
index=1
for( i in unique(groups) ) {
dat3[,index]<-rowSums(data.frame(dat2[,which(groups==i)]))/ncol(data.frame(dat2[,which(groups==i)]))
columnnames<-c(columnnames, paste("group", i, sep=""))
index=index+1
}
FC <- dat3[,2]-dat3[,1]

M
rp.fold.change
FC
```
The result is:
```
> M  #empiricalBayes
[1] -6.5 -5.5 -6.5 -7.5
> rp.fold.change   #RankProd
[1] -6.5 -5.5 -6.5 -7.5
> FC  #calculate-fold-change
[1] 6.5 5.5 6.5 7.5
```
Now we change the group definition by swapping the numbers/identifiers:
```
groups<-c(1,1,2,2)

#Empirical Bayes
pairing <- "EMPTY"
design<-model.matrix(~as.factor(groups))
fit <- lmFit(dat2, design)
fit <- eBayes(fit)
tab <- toptable(fit, coef=2, number=nrow(fit), adjust.method=adj.method, sort.by="none")
p <- tab$adj.P.Val
M <- tab$logFC

#RankProd
dat2.1 <-dat2[,groups==unique(groups)[1]]
dat2.2 <-dat2[,groups==unique(groups)[2]]
rp.fold.change <- apply(dat2.1, 1, mean, na.rm=T) - apply(dat2.2, 1, mean, na.rm=T)

#calculate-fold-change
columnnames<-c()
dat3<-matrix(nrow=nrow(dat2), ncol=length(unique(groups)), NA)
index=1
for( i in unique(groups) ) {
dat3[,index]<-rowSums(data.frame(dat2[,which(groups==i)]))/ncol(data.frame(dat2[,which(groups==i)]))
columnnames<-c(columnnames, paste("group", i, sep=""))
index=index+1
}
FC <- dat3[,2]-dat3[,1]

M
rp.fold.change
FC
```
The result is:
```
> M  #empiricalBayes
[1] 6.5 5.5 6.5 7.5
> rp.fold.change   #RankProd
[1] -6.5 -5.5 -6.5 -7.5
> FC  #calculate-fold-change
[1] 6.5 5.5 6.5 7.5
```
Empirical Bayes changed the sign, the others do not!

Now the same with the modified code:
```
library(multtest)
library(limma)
adj.method<-"BH"
dat2<-matrix(c(1,2,1,2,2,1,2,1,8,7,8,9,8,7,8,9),ncol=4)
dat2
groups<-c(2,2,1,1)

#Empirical Bayes
pairing <- "EMPTY"
gsorted=groups
gsorted[which(groups==unique(groups)[1])]=sort(unique(groups))[1]
gsorted[which(groups==unique(groups)[2])]=sort(unique(groups))[2]
groups=gsorted
design<-model.matrix(~as.factor(groups))
fit <- lmFit(dat2, design)
fit <- eBayes(fit)
tab <- toptable(fit, coef=2, number=nrow(fit), adjust.method=adj.method, sort.by="none")
p <- tab$adj.P.Val
M <- tab$logFC

groups<-c(2,2,1,1)
#RankProd
dat2.1 <-dat2[,groups==unique(groups)[1]]
dat2.2 <-dat2[,groups==unique(groups)[2]]
rp.fold.change <- apply(dat2.2, 1, mean, na.rm=T) - apply(dat2.1, 1, mean, na.rm=T)

#calculate-fold-change
columnnames<-c()
dat3<-matrix(nrow=nrow(dat2), ncol=length(unique(groups)), NA)
index=1
for( i in unique(groups) ) {
dat3[,index]<-rowSums(data.frame(dat2[,which(groups==i)]))/ncol(data.frame(dat2[,which(groups==i)]))
columnnames<-c(columnnames, paste("group", i, sep=""))
index=index+1
}
FC <- dat3[,2]-dat3[,1]

M
rp.fold.change
FC
```
The result is:
```
> M  #empiricalBayes
[1] 6.5 5.5 6.5 7.5
> rp.fold.change   #RankProd
[1] 6.5 5.5 6.5 7.5
> FC  #calculate-fold-change
[1] 6.5 5.5 6.5 7.5
```
Swapping groups:
```
groups<-c(1,1,2,2)

#Empirical Bayes
pairing <- "EMPTY"
gsorted=groups
gsorted[which(groups==unique(groups)[1])]=sort(unique(groups))[1]
gsorted[which(groups==unique(groups)[2])]=sort(unique(groups))[2]
groups=gsorted
design<-model.matrix(~as.factor(groups))
fit <- lmFit(dat2, design)
fit <- eBayes(fit)
tab <- toptable(fit, coef=2, number=nrow(fit), adjust.method=adj.method, sort.by="none")
p <- tab$adj.P.Val
M <- tab$logFC

groups<-c(1,1,2,2)
#RankProd
dat2.1 <-dat2[,groups==unique(groups)[1]]
dat2.2 <-dat2[,groups==unique(groups)[2]]
rp.fold.change <- apply(dat2.2, 1, mean, na.rm=T) - apply(dat2.1, 1, mean, na.rm=T)

#calculate-fold-change
columnnames<-c()
dat3<-matrix(nrow=nrow(dat2), ncol=length(unique(groups)), NA)
index=1
for( i in unique(groups) ) {
dat3[,index]<-rowSums(data.frame(dat2[,which(groups==i)]))/ncol(data.frame(dat2[,which(groups==i)]))
columnnames<-c(columnnames, paste("group", i, sep=""))
index=index+1
}
FC <- dat3[,2]-dat3[,1]

M
rp.fold.change
FC
```
The result is:
```
> M  #empiricalBayes
[1] 6.5 5.5 6.5 7.5
> rp.fold.change   #RankProd
[1] 6.5 5.5 6.5 7.5
> FC  #calculate-fold-change
[1] 6.5 5.5 6.5 7.5
```

Coherent!

### CODE REVIEW

**Comment by chipster-admin** [comment]
Hi Oliver 

and thanks a lot for looking into this. The RankProd method was added later by somebody who worked a short while on Chipster, and we hadn't noticed that it produces FC values (and that they are inconsistent with those produced by empirical Bayes). We will fix the inconsistency asap. 

However, we need to keep the logic of indicating control samples with a smaller number, because this is easier for users than trying to get the samples in a certain order. This approach is taught on all our courses (microarray and NGS), and it is explained also in the phenodata manual (http://chipster.csc.fi/manual/visualisation-phenodata.html). However, I now realize that it is not mentioned in the Two group test -tool's help text and manual, we will add it there as well. 

It is true that the calculate-fold-change.R is based on the grouping of the first sample, but after your changes Max added a parameter that allows the user to tell if the grouping of the first sample should be considered as the control or not. I totally agree with you that this is confusing, and we'll try to clarify that as well. 

Maria and our statistician Seija will look into the RankProd section of the Two group test tool tomorrow and propose a modification to you. Is this method used a lot at DKFZ? 

Thanks again for your help and sorry once more for the confusion, 
Eija

**Comment by oheil** [comment]
> However, we need to keep the logic of indicating control samples with a smaller number, because this is easier for users than trying to get the samples in a certain order. This approach is taught on all our courses (microarray and NGS), and it is explained also in the phenodata manual (http://chipster.csc.fi/manual/visualisation-phenodata.html). However, I now realize that it is not mentioned in the Two group test -tool's help text and manual, we will add it there as well.
> 

Good idea and maybe its the better approach.

> Maria and our statistician Seija will look into the RankProd section of the Two group test tool tomorrow and propose a modification to you.

This would be a solution:
```
dat2.1 <-dat2[,which(groups==sort(unique(groups))[1])]
dat2.2 <-dat2[,which(groups==sort(unique(groups))[2])]
rp.fold.change <- apply(dat2.2, 1, mean, na.rm=T) - apply(dat2.1, 1, mean, na.rm=T)
```
>  Is this method used a lot at DKFZ?
I don't know and I just found the problem now when creating a good code example for you.

> Thanks again for your help and sorry once more for the confusion,
> Eija 

No need for worries!
We (all users here and me) thank you for all the effort and work you put into this great tool!

**Comment by oheil** [comment]
Pull request can be closed.

**Comment by oheil** [comment]
Or you can accept my new master.

> 
It is true that the calculate-fold-change.R is based on the grouping of the first sample, but after your changes Max added a parameter that allows the user to tell if the grouping of the first sample should be considered as the control or not. I totally agree with you that this is confusing, and we'll try to clarify that as well.

I think a new parameter is not the best approach. You should stick the convention that 1 or the lowest number denotes the control/base.

The current master also change calculate-fold-change.R to reflect this.

**Pull request merged**
